{{- if .Values.artifact_registry }}

apiVersion: artifactregistry.cnrm.cloud.google.com/v1beta1
kind: ArtifactRegistryRepository
metadata:
  name: {{ include "lifecycle" . }}-{{ required "REQUIRED: google.artifact_repo" .Values.google.artifact_repo }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" . }}
spec:
  format: DOCKER
  location: {{ .Values.google.region }}

{{- end }}
