{{- if .Values.storage }}

apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: {{ include "public_bucket" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" . }}
    cnrm.cloud.google.com/force-destroy: "false"
spec:
  uniformBucketLevelAccess: true
  cors:
    - origin: ["https://{{- include "domain" $ -}}"]
      responseHeader: ["Content-Type"]
      method: ["GET", "HEAD", "DELETE"]
      maxAgeSeconds: 3600

---

apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: {{ include "etl_bucket" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" . }}
    cnrm.cloud.google.com/force-destroy: "false"
spec:
  uniformBucketLevelAccess: true
  cors:
    - origin: ["https://{{- include "domain" $ -}}"]
      responseHeader: ["Content-Type"]
      method: ["GET", "HEAD", "DELETE"]
      maxAgeSeconds: 3600
  # lifecycleRule:
  #   - action:
  #       type: Delete
  #     condition:
  #       age: 7

{{- end }}
