project: default

destination:
  server: https://kubernetes.default.svc

source:
  path: ""
  repoURL: https://theboarderline.github.io/helm-charts/
  chart: argocd-tenant
  targetRevision: 0.0.4

syncPolicy:
  automated:
    prune: true
    selfHeal: true

syncOptions:
  CreateNamespace: true
  PruneLast: true
