{{- if .Values.app_infra.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-infra
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: app-infra
  source:
    path: charts/app-infra
    repoURL: {{ include "repo_url" . }}
    targetRevision: {{ include "targetRevision" . }}
    helm:
      values: |
        lifecycle: {{ required "REQUIRED: lifecycle" .Values.lifecycle }}
        sa_project_id: {{ include "sa_project_id" . }}
        github_org: {{ required "REQUIRED: github_org" .Values.github_org }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
