apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}
  source:
  {{- if .Values.argocd.source.chart }}
    chart: {{ .Values.argocd.source.chart }}
  {{- else }}
    path: {{ .Values.argocd.source.path }}
  {{- end }}

    repoURL: {{ .Values.argocd.source.repoURL }}
    targetRevision: {{ include "argocd.targetRevision" . }}
  syncPolicy:
    automated:
      prune: {{ .Values.argocd.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.argocd.syncPolicy.automated.selfHeal }}