apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}
  source:
    path: {{ .Values.argocd.source.path }}
    repoURL: {{ .Values.argocd.source.repoURL }}
    targetRevision: {{ .Values.argocd.source.targetRevision }}
  syncPolicy:
    automated:
      prune: {{ .Values.argocd.source.prune }}
      selfHeal: {{ .Values.argocd.source.selfHeal }}