{{- if .Values.workflows.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: argo-workflows
  source:
    path: charts/argo-workflows
    repoURL: {{ include "repo_url" . }}
    targetRevision: {{ include "targetRevision" . }}
    helm:
      values: |
        lifecycle: {{ required "REQUIRED: lifecycle" .Values.lifecycle }}
      valueFiles:
        - "values/{{- required "REQUIRED: lifecycle" .Values.lifecycle -}}.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
