apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}
  source:
    path: {{ .Values.argocd.source.path }}
    repoURL: {{ .Values.argocd.source.repoURL }}
    targetRevision: {{ include "argocd.targetRevision" . }}
    helm:
      values: |
        lifecycle: {{ required "REQUIRED: lifecycle" .Values.lifecycle }}
  syncPolicy:
    automated:
      prune: {{ .Values.argocd.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.argocd.syncPolicy.automated.selfHeal }}