{{- if .Values.events.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: argo-events
  source:
    path: argo-events
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ include "targetRevision" . }}
    helm:
      valueFiles:
        - "values/{{- required "REQUIRED: lifecycle" .Values.lifecycle -}}.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
