# helm upgrade external-secrets external-secrets/kubernetes-external-secrets \
# -i -n external-secrets --create-namespace \
# --set env.POLLER_INTERVAL_MILLISECONDS=$MS
# set annotations

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}
  source:
    chart: {{ .Values.secrets.source.chart }}
    repoURL: {{ .Values.secrets.source.repoURL }}
    targetRevision: {{ .Values.secrets.source.targetRevision }}
  syncPolicy:
    automated:
      prune: {{ .Values.secrets.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.secrets.syncPolicy.automated.selfHeal }}