{{ if .Values.secrets.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.secrets.destination.namespace }}
  source:
    chart: {{ .Values.secrets.source.chart }}
    repoURL: {{ .Values.secrets.source.repoURL }}
    targetRevision: {{ .Values.secrets.source.targetRevision }}
    helm:
      values: |
        env.POLLER_INTERVAL_MILLISECONDS: {{ include "secrets_refresh" . | quote }}
        serviceAccount:
          annotations:
            iam.gke.io/gcp-service-account: gke-worker@{{- .Values.lifecycle -}}-v1-gke-project.iam.gserviceaccount.com
  syncPolicy:
    automated:
      prune: {{ .Values.secrets.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.secrets.syncPolicy.automated.selfHeal }}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
