{{- if .Values.infra_tenants.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-tenants
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: infra-tenants
  source:
    path: charts/infra-tenant
    repoURL: {{ include "repo_url" . }}
    targetRevision: {{ include "targetRevision" . }}
    helm:
      valueFiles:
        - "values/{{- required "REQUIRED: lifecycle" .Values.lifecycle -}}.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=false

{{- end }}
