{{- if .Values.rbac_manager.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac-manager
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: rbac-manager
  source:
    path: charts/rbac-manager
    repoURL: {{ include "repo_url" . }}
    targetRevision: {{ include "targetRevision" . }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
