{{- if .Values.tenant_rbac.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-rbac
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: tenant-rbac
  source:
    path: charts/tenant-rbac
    repoURL: {{ include "repo_url" . }}
    targetRevision: {{ include "targetRevision" . }}
    helm:
      values: |
        lifecycle: {{ required "REQUIRED: lifecycle" .Values.lifecycle }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=false

{{- end }}
