project: default

destination:
  server: https://kubernetes.default.svc

source:
  path: ""
  targetRevision: HEAD

syncPolicy:
  automated:
    prune: true
    selfHeal: true

syncOptions:
  CreateNamespace: true
  PruneLast: true
