project: default

destination:
  server: https://kubernetes.default.svc

source:
  path: ""
  repoURL: https://theboarderline.github.io/helm-charts
  chart: web-app
  targetRevision: 0.0.32

syncPolicy:
  automated:
    prune: true
    selfHeal: true

syncOptions:
  CreateNamespace: true
  PruneLast: true
