{{- if .Values.ingress -}}

apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: argo-workflows-frontendconfig
spec:
  sslPolicy: tls-12
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: argo-workflows-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /healthz
    port: 8080

{{- end -}}
