
apiVersion: v1
kind: Service
metadata:
  name: argo-workflows-svc

{{- if .Values.ingress }}

  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"http":"argo-workflows-backendconfig"}}'
spec:
  type: ClusterIP

{{- else }}

spec:
  type: LoadBalancer

{{- end }}

  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 2746
  selector:
    app.kubernetes.io/name: argo-workflows-server




