proj_identifier: v1

app_code: lg

google:
  domain: lakegames.us

api:
  label: lgames

secrets:
  enabled: true

django:
  enabled: true

sendgrid:
  enabled: true
  email: lakegamescontact@gmail.com

firebase:
  enabled: true

db:
  local: true
