apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wob2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: wob2
    namespace: wob2
    server: https://kubernetes.default.svc
  source:
    path: charts/argocd-platform
    repoURL: https://github.com/theboarderline/helm-charts
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
