apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: platform-cd
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://github.com/theboarderline/helm-charts.git
    targetRevision: HEAD #0.0.6
    chart: argocd-platform
    helm:
      valueFiles:
        - charts/argocd-platform/values/default.yaml
        - charts/argocd-platform/values/dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
