apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: platform-cd
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://theboarderline.github.io/helm-charts
    targetRevision: 0.0.7
    chart: argocd-tenant
    helm:
      valueFiles:
        - values/default.yaml
        - values/dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
