apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wob
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: wob
    namespace: wob
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://github.com/theboarderline/helm-charts
    targetRevision: HEAD
    chart: web-app
    helm:
      values: |
        lifecycle: dev
        domain: colemangroupsolutions.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
