lifecycle: dev
gke_project_id: gke-project
db_project_id: db-project
app_code: test
domain: example.com

import:
  enabled: true

twilio:
  enabled: true
  mock: true
  number: "123456789"
  reply_number: "987654321"

rapid_api:
  enabled: true

groupme:
  enabled: true

deepai:
  enabled: true

cronjob:
  api:
    endpoint: repeat

db:
  proxy: true
