lifecycle: dev
gke_project_id: gke-project
db_project_id: db-project
app_code: test
domain: example.com

linkerd:
  enabled: true

postgres:
  enabled: true

import:
  enabled: true

twilio:
  enabled: true
  mock: true
  number: "123456789"
  reply_number: "987654321"

rapid_api:
  enabled: true

groupme:
  enabled: true

deepai:
  enabled: true

cronjobs:
  enabled: true
  default_schedule: "0 14 * * *"
  jobs:
    - name: job
      enabled: true
      endpoint: endpoint
    - name: disabled-job
      enabled: false
      endpoint: disabled-endpoint

db:
  proxy: true

infobip:
  enabled: true

