enabled: true
local: false

proj_identifier: platform

api:
  enabled: true
  tag: latest
  label: server
  use_pd: false
  pd_size: 5Gi

  memory:
    request: "128Mi"
    limit: "512Mi"
  cpu:
    request: .2
    limit: 1
  replicas: 1
  max_replicas: 5
  target_cpu: 80
  target_mem: 512Mi

nginx:
  enabled: true
  tag: latest
  memory:
    request: "5Mi"
    limit: "50Mi"
  cpu:
    request: .1
    limit: .5
  replicas: 1
  max_replicas: 3
  target_cpu: 80
  target_mem: 50Mi

google:
  region: us-central1
  zone: us-central1-a
  analytics:
    enabled: false

security_policy: us-only
ssl_policy: tls-12

ingress:
  http: false
  https: true

autoscaler:
  enabled: false

secrets:
  enabled: false

cilium:
  enabled: false

django:
  enabled: false
  use_email: false

db:
  proxy: false
  local: true
  proxy_version: gcr.io/cloudsql-docker/gce-proxy:1.21.0

twilio:
  enabled: false

firebase:
  enabled: false

sendgrid:
  enabled: false

agile:
  enabled: false
  replicas: 1


