enabled: true
local: false
non_preemptible: false

github_org: theboarderline

primary_cluster_name: central-cluster
primary_cluster: central-cluster-membership
sa_project_id: tbl-svc-acct-project

api:
  enabled: true
  tag: latest
  containerPort: 8000
  healthCheckPath: /api/
  label: server
  use_pd: false
  disk_size: 10Gi
  memory:
    request: 64Mi
    limit: 256Mi
  cpu:
    request: .1
    limit: 1
  replicas: 1
  max_replicas: 5
  target_cpu: 80
  target_mem: 128Mi

nginx:
  enabled: true
  tag: latest
  containerPort: 3000
  healthCheckPath: /health/
  memory:
    request: 8Mi
    limit: 16Mi
  cpu:
    request: .01
    limit: .25
  replicas: 1
  max_replicas: 3
  target_cpu: 80
  target_mem: 12Mi

importer:
  enabled: false
  tag: latest
  containerPort: 8000
  healthCheckPath: /importer/health/
  memory:
    request: 64Mi
    limit: 256Mi
  cpu:
    request: .1
    limit: 1
  replicas: 1
  max_replicas: 5
  target_cpu: 80
  target_mem: 128Mi

google:
  key: false
  maps:
    enabled: false
  region: us-central1
  zone: us-central1-a
  cdn:
    enabled: false
  config_connector_context: false
  create_ip: false
  create_cloudbuild: false
  create_registry: false
  create_monitoring_suite: false
  notification_channel: "4610371196665423148"
  registry: gcr.io
  sql:
    enabled: false
  storage:
    enabled: true
    create: false
    bucket_list:
      - name: v3-public-content
        key: PUBLIC_BUCKET
        public: true

      - name: v3-backend-bucket
        key: BACKEND_BUCKET
        public: false
  iap:
    enabled: false
    test:
      enabled: false
  analytics:
    enabled: false
  wi_test: false

security_policy: us-only
ssl_policy: tls-12

jwt:
  enabled: false

import:
  enabled: false
  schedule: "0 16 * * 1-6"

oauth:
  google:
    enabled: false
    sheets:
      enabled: false
      path: /backend/secrets

  github:
    enabled: false

  facebook:
    enabled: false

  twitter:
    enabled: false

external_dns:
  enabled: true

external_secrets:
  enabled: true
  refresh_interval: 0

cert_manager:
  enabled: false

ingress:
  enabled: true
  bring_ip: false
  https: true
  cert: false
  mci: false
  nginx: false

fqdn_network_policy:
  enabled: false

network_policy:
  enabled: false

acm:
  enabled: false

autoscaler:
  enabled: false

cilium:
  enabled: false

epsagon:
  enabled: false

django:
  enabled: true
  use_email: false

gin:
  input_path: /tmp/input
  enabled: false

db:
  proxy: false
  proxy_version: gcr.io/cloudsql-docker/gce-proxy:1.33.3

cronjob:
  api:
    endpoint: batch
  image:
    tag: 0.0.3

twilio:
  enabled: false
  flex:
    enabled: false

wiseagent:
  enabled: false

firebase:
  enabled: false

sendgrid:
  enabled: false

airtable:
  enabled: false

openai:
  enabled: false

attom:
  enabled: false

postgres:
  enabled: false
  disk_size: 10Gi
  backup:
    type: "volume"
