enabled: true
local: false

primary_cluster: central-cluster-membership
sa_project_id: tbl-svc-acct-project

api:
  enabled: true
  tag: latest
  label: server
  use_pd: false
  mount_pd: false
  disk_size: 5Gi

  memory:
    request: 64Mi
    limit: 256Mi
  cpu:
    request: .1
    limit: 1

  replicas: 1
  max_replicas: 5
  target_cpu: 80
  target_mem: 128Mi

nginx:
  enabled: true
  tag: latest
  memory:
    request: 5Mi
    limit: 50Mi
  cpu:
    request: .05
    limit: .5
  replicas: 1
  max_replicas: 3
  target_cpu: 80
  target_mem: 50Mi

google:
  region: us-central1
  zone: us-central1-a
  registry: ""
  # registry: app-images
  iap:
    enabled: false
    test:
      enabled: false
  analytics:
    enabled: false

security_policy: us-only
ssl_policy: tls-12

oauth:
  google:
    enabled: false
    sheets:
      enabled: false
      path: /backend/secrets

  github:
    enabled: false

  facebook:
    enabled: false

  twitter:
    enabled: false

external_dns:
  enabled: false

external_secrets:
  enabled: false

cert_manager:
  enabled: false

ingress:
  enabled: true
  https: true
  cert: false
  create_ip: false
  mci: false
  nginx: false

network_policy:
  enabled: false

autoscaler:
  enabled: false

secrets:
  enabled: false

cilium:
  enabled: false

django:
  enabled: true
  use_email: false

gin:
  input_path: /tmp/input
  enabled: false

db:
  proxy: false
  proxy_version: gcr.io/cloudsql-docker/gce-proxy:1.21.0

twilio:
  enabled: false
  flex:
    enabled: false

firebase:
  enabled: false

sendgrid:
  enabled: false

agile:
  enabled: false
  replicas: 1


