enabled: true
local: false
non_preemptible: false

github_org: theboarderline

primary_cluster_name: central-cluster
primary_cluster: central-cluster-membership
sa_project_id: tbl-svc-acct-project

api:
  enabled: true
  tag: latest
  label: server
  use_pd: false
  mount_pd: false
  disk_size: 5Gi

  memory:
    request: 128Mi
    limit: 256Mi
  cpu:
    request: .005
    limit: .5

  replicas: 1
  max_replicas: 5
  target_cpu: 80
  target_mem: 128Mi

nginx:
  enabled: true
  tag: latest
  memory:
    request: 8Mi
    limit: 16Mi
  cpu:
    request: .001
    limit: .025
  replicas: 1
  max_replicas: 3
  target_cpu: 80
  target_mem: 12Mi

google:
  region: us-central1
  zone: us-central1-a
  config_connector_context: false
  create_ip: true
  create_cloudbuild: true
  create_registry: false
  create_storage_buckets: true
  create_monitoring_suite: true
  notification_channel: "4610371196665423148"
  registry: gcr.io
  iap:
    enabled: false
    test:
      enabled: false
  analytics:
    enabled: false

security_policy: us-only
ssl_policy: tls-12

oauth:
  google:
    enabled: false
    sheets:
      enabled: false
      path: /backend/secrets

  github:
    enabled: false

  facebook:
    enabled: false

  twitter:
    enabled: false

external_dns:
  enabled: true

external_secrets:
  enabled: true
  refresh_interval: 0

cert_manager:
  enabled: false

ingress:
  enabled: true
  https: true
  cert: false
  mci: false
  nginx: false

network_policy:
  enabled: false

autoscaler:
  enabled: false

cilium:
  enabled: false

epsagon:
  enabled: false

django:
  enabled: true
  use_email: false

gin:
  input_path: /tmp/input
  enabled: false

db:
  proxy: false
  proxy_version: gcr.io/cloudsql-docker/gce-proxy:1.30.1

twilio:
  enabled: false
  flex:
    enabled: false

firebase:
  enabled: false

sendgrid:
  enabled: false

agile:
  enabled: false
  replicas: 1


