{{- if and (.Values.enabled) (.Values.agile.enabled) }}

apiVersion: v1
kind: Service
metadata:
  name: agile-svc
  labels:
    app: agile-svc
    tier: backend
  {{- if not .Values.local }}
  annotations:
    cloud.google.com/backend-config: '{"default": "gke-backendconfig"}'
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: agile-dep
    
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000

{{- end }}
