{{- if and (.Values.enabled) (.Values.agile.enabled) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: agile-dep
  labels:
    app: agile-dep
    tier: backend
spec:
  replicas: {{ required "agile Replicas required" .Values.agile.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: agile-dep
  template:
    metadata:
      labels:
        app: agile-dep
    spec:
      serviceAccountName: {{ .Values.namespace -}}-sa
      restartPolicy: Always
      containers:
      - name: agile
        image: {{ include "agile_image" . }}
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: {{ required "api Memory Requests Required" .Values.api.memory.request }}
            cpu: {{ required "api CPU Requests Required" .Values.api.cpu.request }}
          limits:
            memory: {{ required "api Memory Limits Required" .Values.api.memory.limit }}
            cpu: {{ required "api CPU Limits Required" .Values.api.cpu.limit }}

        # livenessProbe:
        #   httpGet:
        #     path: /healthz/
        #     port: 3001
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #
        # readinessProbe:
        #   httpGet:
        #     path: /healthz/
        #     port: 3001
        #   initialDelaySeconds: 30
        #   periodSeconds: 10

        env:
        - name: LIFECYCLE
          value: {{ .Values.lifecycle }}
        - name: DOMAIN
          value: {{ include "domain" . }}
        - name: PRIVATE_BUCKET
          value: {{ include "private_bucket" . }}

        - name: AGILE_CRM_REST_KEY
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: agile-crm-rest-key


        {{- if eq .Values.namespace "coleman" }}
        - name: TWILIO_NUMBER_IL
          value: '{{ required "IL Phone number required for CGS" .Values.twilio.numbers.il }}'
        - name: TWILIO_NUMBER_WA
          value: '{{ required "WA Phone number required for CGS" .Values.twilio.numbers.wa }}'
        - name: TWILIO_NUMBER_SID_IL
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: twilio-number-sid-il
        - name: TWILIO_NUMBER_SID_WA
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: twilio-number-sid-wa

        {{- else }}
        - name: TWILIO_NUMBER
          value: '{{ required "Phone number required if using Twilio" .Values.twilio.number }}'
        - name: TWILIO_NUMBER_SID
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: twilio-number-sid
        {{- end }}

        ports:
        - containerPort: 3001
          name: agile-port


{{- end }}


