{{- if and (.Values.enabled) (.Values.api.enabled) }}

apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    app: api-svc
    tier: backend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "gke-backendconfig"}'
spec:
  type: ClusterIP
  selector:
    app: api-dep
    
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000

{{- end }}
