{{- if and (.Values.enabled) (.Values.api.enabled) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dep
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    tier: backend
    backstage.io/kubernetes-id: {{ .Values.app_code }}
spec:
  replicas: {{ required "REQUIRED: api.replicas" .Values.api.replicas }}
  selector:
    matchLabels:
      app: api-dep
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        container.apparmor.security.beta.kubernetes.io/api: runtime/default
        container.seccomp.security.alpha.kubernetes.io/api: runtime/default
      labels:
        app: api-dep
        namespace: {{ .Release.Namespace }}
        tier: backend
        backstage.io/kubernetes-id: {{ .Values.app_code }}
    spec:
      tolerations:
      {{- if .Values.non_preemptible }}
      - key: general
      {{- else }}
      - key: preemptible
      {{- end }}
        operator: Equal
        value: "true"
        effect: PreferNoSchedule

      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        runAsUser: 115
        runAsGroup: 125
        fsGroup: 190
        supplementalGroups:
          - 150

      volumes:
        - name: tmp-dir
          emptyDir: {}
        - name: usr-tmp-dir
          emptyDir: {}
        - name: var-tmp-dir
          emptyDir: {}

        - name: app-secrets
          secret:
            secretName: app-secrets

        {{- if .Values.api.use_pd }}
        - name: db-volume
          persistentVolumeClaim:
            claimName: gce-pvc
        {{- end }}

      serviceAccountName: {{ include "ksa_name" . }}
      restartPolicy: Always
      containers:
      - name: api
        image: {{ include "api_image" . }}
        imagePullPolicy: Always

        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          procMount: default
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault

        resources:
          requests:
            memory: {{ required "REQUIRED: api.memory.request" .Values.api.memory.request }}
            cpu: {{ required "REQUIRED: api.cpu.request" .Values.api.cpu.request }}
          limits:
            memory: {{ required "REQUIRED: api.memory.limit" .Values.api.memory.limit }}
            cpu: {{ required "REQUIRED: api.cpu.limit" .Values.api.cpu.limit }}

        volumeMounts:
          {{- if .Values.api.use_pd }}
          - mountPath: /backend/var
            name: db-volume
          {{- end }}
          - mountPath: /tmp
            name: tmp-dir
          - mountPath: /usr/tmp
            name: usr-tmp-dir
          - mountPath: /var/tmp
            name: var-tmp-dir

        {{- if ne .Values.app_code "boatload" }}
        livenessProbe:
          httpGet:
            path: {{ .Values.api.healthCheckPath }}
            port: {{ .Values.api.containerPort }}
          initialDelaySeconds: 30
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: {{ .Values.api.healthCheckPath }}
            port: {{ .Values.api.containerPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
        {{- end }}

        env:
        - name: LIFECYCLE
          value: {{ include "lifecycle" $ }}
        - name: IS_LOCAL
          value: "false"
        - name: USE_GCS
          value: "true"
        - name: DOMAIN
          value: {{ include "subdomain" $ }}

        {{- if .Values.django.verify_email }}
        - name: VERIFY_EMAIL
          value: "true"
        {{- end }}

        {{- if .Values.google.storage.enabled }}
        {{- range .Values.google.storage.bucket_list }}
        - name: {{ .key }}
          value: {{ include "app_label" $ -}}-{{- .name }}
        {{- end }}
        {{- end }}


        {{- if .Values.api.env }}
{{- toYaml .Values.api.env | nindent 8 }}
        {{- end }}

        {{- if .Values.jwt.enabled }}
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret-key
        {{- end }}

        {{- if .Values.gin.enabled }}
        - name: GIN_MODE
          value: release
        {{- if .Values.gin.input_path }}
        - name: INPUT_PATH
          value: {{ .Values.gin.input_path }}
        {{- end }}
        {{- end }}

        {{- if .Values.use_oauth }}
        - name: OAUTH_ID
          valueFrom:
            secretKeyRef:
              name: oauth-credentials
              key: client_id
        - name: OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-credentials
              key: client_secret
        {{- end }}

        {{- if .Values.django.enabled }}

        {{- if .Values.django.email }}
        - name: DJANGO_EMAIL
          value: {{ .Values.django.email }}
        {{- end }}

        - name: DJANGO_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: django-key

        {{- if .Values.django.oauth_id }}
        - name: OAUTH_ID
          value: {{ .Values.django.oauth_id }}

        - name: OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: oauth-secret
        {{- end }}

        {{- end }}

        {{ if .Values.oauth.google.enabled }}
        - name: GOOGLE_OAUTH_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: google-oauth-id

        - name: GOOGLE_OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: google-oauth-secret
        {{ end }}

        {{- if .Values.oauth.google.sheets.enabled }}
        - name: OAUTH_JSON_PATH
          value: /backend/secrets/google-oauth-creds
        {{- end }}

        {{- if .Values.oauth.github.enabled }}
        - name: GITHUB_OAUTH_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: github-oauth-id

        - name: GITHUB_OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: github-oauth-secret
        {{- end }}

        {{- if .Values.oauth.facebook.enabled }}
        - name: FACEBOOK_OAUTH_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: facebook-oauth-id

        - name: FACEBOOK_OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: facebook-oauth-secret
        {{- end }}

        {{- if .Values.oauth.twitter.enabled }}
        - name: TWITTER_OAUTH_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: twitter-api-key

        - name: TWITTER_OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: twitter-api-key-secret
        {{- end }}

        {{- if .Values.sendgrid.enabled }}
        - name: SENDGRID_EMAIL
          value: {{ .Values.sendgrid.email }}

        - name: SENDGRID_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: sendgrid-key
        {{- end }}

        {{- if .Values.db.proxy }}
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_NAME
          value: {{ include "db_name" . }}
        - name: DB_USER
          value: {{ include "app_sa" . }}
        - name: DB_PASSWORD
          value: fake-password
        {{- end }}

        {{- if .Values.postgres.enabled }}
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: crunchydb-pguser-crunchydb
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: crunchydb-pguser-crunchydb
              key: port
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: crunchydb-pguser-crunchydb
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: crunchydb-pguser-crunchydb
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: crunchydb-pguser-crunchydb
              key: password
        {{- end }}

        {{- if .Values.twilio.enabled }}
        - name: TWILIO_NUMBER
          value: '{{ required "REQUIRED: twilio.number" .Values.twilio.number }}'

        - name: TWILIO_REPLY_NUMBER
          value: '{{ required "REQUIRED: twilio.reply_number" .Values.twilio.reply_number }}'

        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: twilio-account-sid

        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: twilio-auth-token

        {{- if .Values.twilio.flex.enabled }}
        - name: FLEX_WORKSPACE_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: twilio-flex-workspace-id

        - name: FLEX_WORKFLOW_SID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: twilio-flex-workflow-sid
        {{- end }}

        {{- end }}

        {{- if .Values.wiseagent.enabled }}
        - name: WISE_AGENT_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: wise-agent-key

        - name: WISE_AGENT_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: wise-agent-auth-token
        {{- end }}

        {{- if .Values.airtable.enabled }}
        - name: BASE_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: base-id
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: api-key
        {{- end }}

        ports:
        - containerPort: {{ .Values.api.containerPort }}
          name: api-port

      {{- if .Values.db.proxy }}
      - name: proxy
        image: "{{ .Values.db.proxy_version }}"
        imagePullPolicy: Always
        command:
        - /cloud_sql_proxy
        - -instances={{- include "db_project" . -}}:{{- required "REQUIRED: google.region" .Values.google.region -}}:{{- include "instance_name" . }}=tcp:127.0.0.1:5432
        - -enable_iam_login

        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          procMount: default
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      {{- end }}

{{- end }}


