{{- if and (.Values.enabled) (.Values.api.enabled) }}

apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    tier: backend
    backstage.io/kubernetes-id: {{ .Values.app_code }}
  {{- if not .Values.local }}
  annotations:
    cloud.google.com/backend-config: '{"default": "gke-backendconfig"}'
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: api-dep
    
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.api.containerPort }}

{{- end }}
