{{- if and (.Values.enabled) (not .Values.local) }}

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gke-backendconfig
spec:
  securityPolicy:
    name: {{ .Values.security_policy }}

  {{- if .Values.google.iap }}
  iap:
    enabled: {{ .Values.google.enable_iap }}
    oauthClientCredentials:
      secretName: oauth-credentials
  {{- end }}

  {{- if and (ne .Values.lifecycle "ops") (ne .Values.lifecycle "dev") }}
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
  {{- end }}

{{- end }}
