{{- if and (.Values.enabled) (not .Values.local) }}
{{- if .Values.cilium.enabled }}

apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-kube-dns
spec:
  endpointSelector:
    matchLabels: {}
  egress:
    - toFQDNs:
        - matchPattern: "*.{{- .Values.namespace -}}.svc"

    - toEndpoints:
        - matchLabels:
            "k8s:k8s-app": kube-dns
            "k8s:io.kubernetes.pod.namespace": kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: TCP
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"

{{- end }}
{{- end }}
