{{- if and (.Values.enabled) (not .Values.local) }}
{{- if .Values.cilium.enabled }}

apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: api-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: api-dep
  egress:
    - to:
      - fqdns:
        - "googleapis.com"
        - "*.googleapis.com"
        - "accounts.google.com"
      ports:
      - port: 443
        protocol: TCP

  ingress:
    - from:
      - cidrs:
        - "130.211.0.0/22"
        - "35.191.0.0/16"
      ports:
      - port: 443
        protocol: TCP
      toPorts:
        - ports:
          - port: "443"
            protocol: TCP
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
    - toEndpoints:
        - matchLabels:
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: TCP
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toCIDR:
        - "130.211.0.0/22"
        - "35.191.0.0/16"
    - toCIDR:
        - "127.0.0.1/32"
      toPorts:
        - ports:
            - port: "988"
              protocol: TCP
    - toCIDR:
        - "169.254.169.254/32"
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP

{{- end }}
{{- end }}
