{{- if and (.Values.enabled) (not .Values.local) }}
{{- if .Values.cilium.enabled }}

apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: gce-metadata-server
spec:
  endpointSelector:
    matchLabels: {}
  egress:
    - toCIDR:
        - "169.254.169.254/32"
    - toEndpoints:
        - matchLabels: {}
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP

{{- end }}
{{- end }}
