{{- if and (.Values.enabled) (not .Values.local) }}
{{- if .Values.cilium.enabled }}

apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-kube-system
spec:
  endpointSelector: {}

  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system

{{- end }}
{{- end }}
