{{- if .Values.google.config_connector.enabled }}
{{- if .Values.google.create_cloudbuild }}

apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: {{ include "app_label" $ -}}-cicd
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project" . }}
  labels:
    namespace: {{ .Release.Namespace }}
    backstage.io/kubernetes-id: {{ .Values.app_code }}
spec:
  disabled: {{ not .Values.enabled }}
  github:
    owner: {{ required "REQUIRED: github_org" .Values.github_org }}
    name: {{ required "REQUIRED: app_code" .Values.app_code }} 
    push:
      branch: "^{{- include "branch" . -}}$"
  # serviceAccountRef:
  #   external: {{ include "cicd_sa" $ }}
  includedFiles:
    - "src/**"
    - "deploy/**"
    {{- if .Values.selenium.enabled }}
    - "selenium/**"
    {{- end }}
  build:
    timeout: 1800s
    options:
      logging: LEGACY
    #   {{- if false }}
    #   machineType: E2_HIGHCPU_8
    #   {{- end }}

    step:
      - id: "Build-API"
        name: "gcr.io/kaniko-project/executor:latest"
        args:
          - --destination={{- include "api_registry" . }}:$COMMIT_SHA
          - --destination={{- include "api_registry" . }}:latest
          - --context=./src/api
          - --cache=true
          - --cache-ttl=240h

      - id: "Build-React"
        name: "gcr.io/kaniko-project/executor:latest"
        args:
          - --destination={{- include "nginx_registry" . }}:$COMMIT_SHA
          - --destination={{- include "nginx_registry" . }}:latest
          - --context=./src/react
          - --cache=true
          - --cache-ttl=240h

      {{- if .Values.selenium.enabled }}
      - id: "Build-Selenium"
        name: "gcr.io/kaniko-project/executor:latest"
        args:
          - --destination={{- include "selenium_registry" . }}:$COMMIT_SHA
          - --destination={{- include "selenium_registry" . }}:latest
          - --context=./src/selenium
          - --cache=true
          - --cache-ttl=240h
      {{- end }}

      - id: Gcloud
        name: "gcr.io/cloud-builders/gcloud-slim"
        entrypoint: "bash"
        args:
          - "-c"
          - |
            gcloud container clusters get-credentials {{ include "primary_cluster_name" $ }} --zone={{- required "REQUIRED: google.zone" $.Values.google.zone }} --project={{- include "gke_project" $ }}

      - id: Helm-Upgrade
        name: gcr.io/walker-cpl/helm
        entrypoint: bash
        args:
          - "-c"
          - |
            helm dep update ./deploy/web-app &&
            helm template {{ include "app_label" $ }} ./deploy/web-app -f ./deploy/values/values.yaml -f ./deploy/values/{{- include "lifecycle" $ -}}.yaml -n {{ include "app_label" $ }} --set web-app.lifecycle={{- include "lifecycle" $ }} --set web-app.api.tag=$COMMIT_SHA --set web-app.nginx.tag=$COMMIT_SHA --set web-app.selenium.tag=$COMMIT_SHA --set web-app.gke_project_id={{- include "gke_project" . }} --set web-app.db_project_id={{- include "db_project" $ }} --set web-app.app_code={{- $.Values.app_code }} --set web-app.domain={{- include "domain" $ }} &&
            helm upgrade -i {{ include "app_label" $ }} ./deploy/web-app -f ./deploy/values/values.yaml -f ./deploy/values/{{- include "lifecycle" $ -}}.yaml -n {{ include "app_label" $ }} --create-namespace --set web-app.lifecycle={{- include "lifecycle" $ }} --set web-app.api.tag=$COMMIT_SHA --set web-app.nginx.tag=$COMMIT_SHA --set web-app.selenium.tag=$COMMIT_SHA --set web-app.gke_project_id={{- include "gke_project" . }} --set web-app.db_project_id={{- include "db_project" $ }} --set web-app.app_code={{- $.Values.app_code }} --set web-app.domain={{- include "domain" $ }}
        env:
          - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
          - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"

{{- end }}
{{- end }}

