{{- if .Values.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: react-config
  namespace: {{ .Release.Namespace }}
data:
  env.js: |
    window.LIFECYCLE = '{{- include "lifecycle" $ -}}';
    {{- range .Values.google.storage.bucket_list }}
    window.{{ .key }} = {{ include "app_label" $ -}}-{{- .name }};
    {{- end }}
    {{- if .Values.api.enabled }}
    window.API_URL = 'https://{{- include "subdomain" . -}}/';
    {{- end }}
    {{- if .Values.firebase.enabled }}
    window.AUTH_DOMAIN = '{{- include "app_project" . -}}.firebaseapp.com';
    {{- end }}
    {{- if .Values.google.number }}
    window.GOOGLE_NUMBER = '{{- .Values.google.number -}}';
    {{- end }}

---

{{- if .Values.api.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Release.Namespace }}
data:
  api.conf: |
    location /api/ {
        proxy_set_header Host {{ include "subdomain" . -}};
        proxy_pass http://api-svc.{{- .Release.Namespace -}}.svc;
    }
    location /admin/ {
        proxy_set_header Host {{ include "subdomain" . -}};
        proxy_pass http://api-svc.{{- .Release.Namespace -}}.svc;
    }
    location /redirect/ {
        proxy_set_header Host {{ include "subdomain" . -}};
        proxy_pass http://api-svc.{{- .Release.Namespace -}}.svc;
    }
    location /accounts/ {
        proxy_set_header Host {{ include "subdomain" . -}};
        proxy_pass http://api-svc.{{- .Release.Namespace -}}.svc;
    }

{{- end }}

{{- end }}
