{{- if and (.Values.enabled) (.Values.crm.enabled) }}
{{- if not .Values.ingress.mci }}

apiVersion: v1
kind: Service
metadata:
  name: crm-svc
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    tier: frontend
    backstage.io/kubernetes-id: {{ .Values.app_code }}
  {{- if not .Values.local }}
  annotations:
    cloud.google.com/backend-config: '{"default": "gke-backendconfig"}'
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: crm-dep
    
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.crm.containerPort }}

{{- end }}
{{- end }}
