{{- if .Values.import.enabled }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-data
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: http
            image: apline/httpie
            args: ['/bin/sh', '-c', 'http api-svc.{{- .Release.Namespace -}}.svc/api/batch/  key=$API_KEY']
            env:
            - name: API_KEY
              {{- if .Values.external_secrets.enabled }}
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: django-key
              {{- else }}
              value: 'fake-key'
              {{- end }}
          restartPolicy: OnFailure

{{- end }}
