{{- if .Values.import.enabled }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-data
spec:
  schedule: "{{- .Values.import.schedule -}}"
  jobTemplate:
    spec:
      template:
        spec:
          hostIPC: false
          hostNetwork: false
          hostPID: false
          securityContext:
            runAsUser: 115
            runAsGroup: 125
            fsGroup: 190
            supplementalGroups:
              - 150
          restartPolicy: Never
          containers:
          - name: http
            image: alpine/httpie
            imagePullPolicy: IfNotPresent

            securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              procMount: default
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault

            args:
            - api-svc.{{- .Release.Namespace -}}.svc/api/batch
            - key=$(API_KEY)
            - --ignore-stdin

            env:
            - name: API_KEY
              {{- if .Values.external_secrets.enabled }}
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: django-key
              {{- else }}
              value: 'fake-key'
              {{- end }}

{{- end }}
