{{- if .Values.import.enabled }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-data
spec:
  schedule: "{{- .Values.import.schedule -}}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl
            args:
            - '/bin/sh'
            - '-c'
            - 'curl api-svc.{{- .Release.Namespace -}}.svc/api/batch -d "key=$API_KEY" -v'
            env:
            - name: API_KEY
              {{- if .Values.external_secrets.enabled }}
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: django-key
              {{- else }}
              value: 'fake-key'
              {{- end }}
          restartPolicy: OnFailure

{{- end }}
