{{- if .Values.cronjobs.enabled }}

{{- range .Values.cronjobs.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-{{ .name }}
  labels:
    {{- if $.Values.linkerd.enabled }}
    linkerd.io/inject: enabled
    {{- end }}
spec:
  {{- if .schedule }}
  schedule: "{{- .schedule -}}"
  {{- else }}
  schedule: "{{- $.Values.cronjobs.default_schedule -}}"
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          hostIPC: false
          hostNetwork: false
          hostPID: false
          securityContext:
            runAsUser: 115
            runAsGroup: 125
            fsGroup: 190
            supplementalGroups:
              - 150
          restartPolicy: Never
          containers:
          - name: http
            image: gcr.io/walker-cpl/httpie:0.0.3
            imagePullPolicy: IfNotPresent

            securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              procMount: default
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault

            args:
            - api-svc.{{- $.Release.Namespace -}}.svc/api/{{- .endpoint }}
            - key=$(API_KEY)
            - --ignore-stdin

            env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
            {{- if $.Values.django.enabled }}
                  key: django-key
            {{- else }}
                  key: secret-key
            {{- end }}

---

{{- end }}

{{- end }}

