{{- if .Values.import.enabled }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-data
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl
            args: ['/bin/sh', '-c', 'curl https://{{- include "subdomain" $ -}}/api/batch -d "key=$API_KEY"']
            env:
            - name: API_KEY
              {{- if .Values.external_secrets.enabled }}
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: django-key
              {{- else }}
              value: 'fake-key'
              {{- end }}
          restartPolicy: OnFailure

{{- end }}
