{{- if and (.Values.enabled) (not .Values.local) }}
{{- if .Values.external_secrets.enabled }}

apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secret-store
  namespace: {{ .Release.Namespace }}
spec:
  controller: {{ .Values.app_code }}
  provider:
    gcpsm:
      projectID: {{ include "app_project" $ }}

---

{{- if or (.Values.google.iap.enabled) (.Values.google.iap.test.enabled) }}

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: oauth-credentials
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.external_secrets.refresh_interval }}
  refreshInterval: {{ .Values.external_secrets.refresh_interval }}
  {{- end }}
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: oauth-credentials
    creationPolicy: Owner
  data:
  - secretKey: client_id
    remoteRef:
      key: oauth-id
  - secretKey: client_secret
    remoteRef:
      key: oauth-secret

---

{{- end }}


apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.external_secrets.refresh_interval }}
  refreshInterval: {{ .Values.external_secrets.refresh_interval }}
  {{- end }}
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
  {{- if .Values.django.enabled }}
  - secretKey: django-key
    remoteRef:
      key: django-key
  {{- end }}

  {{- if .Values.firebase.enabled }}
  - secretKey: firebase-key
    remoteRef:
      key: firebase-key
  {{- end }}

  {{- if .Values.oauth.google.sheets.enabled }}
  - secretKey: google-oauth-creds
    remoteRef:
      key: google-oauth-creds
  {{- end }}

  {{- if .Values.sendgrid.enabled }}
  - secretKey: sendgrid-key
    remoteRef:
      key: sendgrid-key
  {{- end }}

  {{- if .Values.twilio.enabled }}
  - secretKey: twilio-account-sid
    remoteRef:
      key: twilio-account-sid

  - secretKey: twilio-auth-token
    remoteRef:
      key: twilio-auth-token

  {{- if .Valies.twilio.flex.enabled }}
  - secretKey: twilio-flex-workspace-id
    remoteRef:
      key: twilio-flex-workspace-id

  - secretKey: twilio-flex-workflow-sid
    remoteRef:
      key: twilio-flex-workflow-sid
  {{- end }}

  {{- end }}

  {{- if .Values.agile.enabled }}
  - secretKey: agile-crm-rest-key
    remoteRef:
      key: agile-crm-rest-key
  {{- end }}

  {{- if eq .Values.app_code "boatload" }}
  - secretKey: api-key
    remoteRef:
      key: api-key
  {{- end }}

{{- end }}
{{- end }}


