{{- if and (.Values.enabled) (not .Values.local) }}
{{- if .Values.external_secrets.enabled }}

apiVersion: external-secrets.io/v1beta1 
kind: SecretStore
metadata:
  name: secret-store
  namespace: {{ .Release.Namespace }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.app_code }}
spec:
  provider:
    gcpsm:
      projectID: {{ include "app_project" $ }}

---

{{- if or (.Values.google.iap.enabled) (.Values.google.iap.test.enabled) }}

apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: oauth-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.app_code }}
spec:
  {{- if .Values.external_secrets.refresh_interval }}
  refreshInterval: {{ .Values.external_secrets.refresh_interval }}
  {{- end }}
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: oauth-credentials
    creationPolicy: Owner
  data:
  - secretKey: client_id
    remoteRef:
      key: oauth-id
  - secretKey: client_secret
    remoteRef:
      key: oauth-secret

---

{{- end }}


apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.external_secrets.refresh_interval }}
  refreshInterval: {{ .Values.external_secrets.refresh_interval }}
  {{- end }}
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    {{- if .Values.jwt.enabled }}
    - secretKey: secret-key
      remoteRef:
        key: secret-key
    {{- end }}

    {{- if .Values.django.enabled }}
    - secretKey: django-key
      remoteRef:
        key: django-key
    {{- end }}

    {{- if .Values.realty_mole.enabled }}
    - secretKey: realty-mole-api-key
      remoteRef:
        key: realty-mole-api-key
    {{- end }}

    {{- if .Values.attom.enabled }}
    - secretKey: attom-data-api-key
      remoteRef:
        key: attom-data-api-key
    {{- end }}

    {{- if .Values.openai.enabled }}
    - secretKey: openai-key
      remoteRef:
        key: openai-key
    {{- end }}

    {{- if .Values.wiseagent.enabled }}
    - secretKey: wise-agent-key
      remoteRef:
        key: wise-agent-key
    - secretKey: wise-agent-auth-token
      remoteRef:
        key: wise-agent-auth-token
    {{- end }}

    {{- if .Values.oauth.google.enabled }}
    - secretKey: google-oauth-id
      remoteRef:
        key: google-oauth-id

    - secretKey: google-oauth-secret
      remoteRef:
        key: google-oauth-secret
    {{- end }}

    {{- if .Values.oauth.github.enabled }}
    - secretKey: github-oauth-id
      remoteRef:
        key: github-oauth-id

    - secretKey: github-oauth-secret
      remoteRef:
        key: github-oauth-secret
    {{- end }}

    {{- if .Values.oauth.facebook.enabled }}
    - secretKey: facebook-oauth-id
      remoteRef:
        key: facebook-oauth-id

    - secretKey: facebook-oauth-secret
      remoteRef:
        key: facebook-oauth-secret
    {{- end }}

    {{- if .Values.oauth.twitter.enabled }}
    - secretKey: twitter-api-key
      remoteRef:
        key: twitter-api-key

    - secretKey: twitter-api-key-secret
      remoteRef:
        key: twitter-api-key-secret
    {{- end }}

    {{- if .Values.firebase.enabled }}
    - secretKey: firebase-key
      remoteRef:
        key: firebase-key
    {{- end }}

    {{- if .Values.sendgrid.enabled }}
    - secretKey: sendgrid-key
      remoteRef:
        key: sendgrid-key
    {{- end }}

    {{- if .Values.twilio.enabled }}
    - secretKey: twilio-auth-token
      remoteRef:
        key: twilio-auth-token

    - secretKey: twilio-account-sid
      remoteRef:
        key: twilio-account-sid

    {{- if .Values.twilio.flex.enabled }}
    - secretKey: twilio-flex-workspace-id
      remoteRef:
        key: twilio-flex-workspace-id

    - secretKey: twilio-flex-workflow-sid
      remoteRef:
        key: twilio-flex-workflow-sid
    {{- end }}

    {{- end }}

    {{- if .Values.airtable.enabled }}
    - secretKey: base-id
      remoteRef:
    {{- if ne .Values.lifecycle "prod" }}
        key: nonprod-base-id
    {{- else }}
        key: base-id
    {{- end }}

    - secretKey: api-key
      remoteRef:
    {{- if ne .Values.lifecycle "prod" }}
        key: nonprod-api-key
    {{- else }}
        key: api-key
    {{- end }}

    {{- end }}

{{- end }}
{{- end }}


