{{- if and (.Values.enabled) (not .Values.local) }}
{{- if .Values.external_secrets.enabled }}

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secret-store
  namespace: {{ .Release.Namespace }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.app_code }}
spec:
  provider:
    gcpsm:
      projectID: {{ include "app_project" $ }}
      {{- if .Values.google.gke_project }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.google.zone }}
          clusterName: {{ .Values.primary_cluster_name }}
          clusterProjectID: {{ .Values.google.gke_project }}
          serviceAccountRef:
            name: {{ .Values.app_code }}-sa
      {{- end }}

---

{{- if or (.Values.google.iap.enabled) (.Values.google.iap.test.enabled) }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.app_code }}
spec:
  {{- if .Values.external_secrets.refresh_interval }}
  refreshInterval: {{ .Values.external_secrets.refresh_interval }}
  {{- end }}
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: oauth-credentials
    creationPolicy: Owner
  data:
  - secretKey: client_id
    remoteRef:
      key: {{ .Values.external_secrets.secret_prefix }}oauth-id
  - secretKey: client_secret
    remoteRef:
      key: {{ .Values.external_secrets.secret_prefix }}oauth-secret

---

{{- end }}


apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.external_secrets.refresh_interval }}
  refreshInterval: {{ .Values.external_secrets.refresh_interval }}
  {{- end }}
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    {{- if .Values.jwt.enabled }}
    - secretKey: secret-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}secret-key
    {{- end }}

    {{- if .Values.django.enabled }}
    - secretKey: django-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}django-key
    {{- end }}

    {{- if .Values.rapid_api.enabled }}
    - secretKey: rapid-api-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}rapid-api-key
    {{- end }}

    {{- if .Values.stripe.enabled }}
    - secretKey: stripe-secret-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}stripe-secret-key
    - secretKey: stripe-public-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}stripe-public-key
    - secretKey: stripe-signing-secret
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}stripe-signing-secret
    {{- end }}

    {{- if .Values.attom.enabled }}
    - secretKey: attom-data-api-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}attom-data-api-key
    {{- end }}

    {{- if .Values.openai.enabled }}
    - secretKey: openai-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}openai-key
    {{- end }}

    {{- if .Values.deepai.enabled }}
    - secretKey: deepai-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}deepai-key
    {{- end }}

    {{- if .Values.groupme.enabled }}
    - secretKey: groupme-access-token
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}groupme-access-token
    {{- end }}

    {{- if .Values.wiseagent.enabled }}
    - secretKey: wise-agent-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}wise-agent-key
    - secretKey: wise-agent-auth-token
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}wise-agent-auth-token
    {{- end }}

    {{- if .Values.oauth.google.enabled }}
    - secretKey: google-oauth-id
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}google-oauth-id

    - secretKey: google-oauth-secret
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}google-oauth-secret
    {{- end }}

    {{- if .Values.oauth.github.enabled }}
    - secretKey: github-oauth-id
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}github-oauth-id

    - secretKey: github-oauth-secret
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}github-oauth-secret
    {{- end }}

    {{- if .Values.oauth.facebook.enabled }}
    - secretKey: facebook-oauth-id
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}facebook-oauth-id

    - secretKey: facebook-oauth-secret
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}facebook-oauth-secret
    {{- end }}

    {{- if .Values.oauth.twitter.enabled }}
    - secretKey: twitter-api-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}twitter-api-key

    - secretKey: twitter-api-key-secret
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}twitter-api-key-secret
    {{- end }}

    {{- if .Values.firebase.enabled }}
    - secretKey: firebase-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}firebase-key
    {{- end }}

    {{- if .Values.sendgrid.enabled }}
    - secretKey: sendgrid-key
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}sendgrid-key
    {{- end }}

    {{- if .Values.twilio.enabled }}
    - secretKey: twilio-auth-token
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}twilio-auth-token

    - secretKey: twilio-account-sid
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}twilio-account-sid

    {{- if .Values.twilio.flex.enabled }}
    - secretKey: twilio-flex-workspace-id
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}twilio-flex-workspace-id

    - secretKey: twilio-flex-workflow-sid
      remoteRef:
        key: {{ .Values.external_secrets.secret_prefix }}twilio-flex-workflow-sid
    {{- end }}

    {{- end }}

    {{- if .Values.airtable.enabled }}
    - secretKey: base-id
      remoteRef:
    {{- if ne .Values.lifecycle "prod" }}
        key: {{ .Values.external_secrets.secret_prefix }}nonprod-base-id
    {{- else }}
        key: {{ .Values.external_secrets.secret_prefix }}base-id
    {{- end }}

    - secretKey: api-key
      remoteRef:
    {{- if ne .Values.lifecycle "prod" }}
        key: {{ .Values.external_secrets.secret_prefix }}nonprod-api-key
    {{- else }}
        key: {{ .Values.external_secrets.secret_prefix }}api-key
    {{- end }}

    {{- end }}

    {{- range .Values.external_secrets.extra_keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.external_secrets.secret_prefix }}{{ . }}
    {{- end }}

{{- end }}
{{- end }}


