{{- if and (.Values.enabled) (not .Values.local) }}

apiVersion: networking.gke.io/v1
kind: FrontendConfig
metadata:
  name: gke-frontendconfig
  namespace: {{ .Release.Namespace }}
  annotations:
    configsync.gke.io/cluster-name-selector: {{ include "primary_cluster" $ }}
spec:
  sslPolicy: {{ .Values.ssl_policy }}
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT

{{- end }}
