{{- if .Values.enabled }}

apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: gke-frontendconfig
spec:
  sslPolicy: {{ .Values.ssl_policy }}
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT

{{- end }}
