{{- if and .Values.enabled .Values.google.federation.audience }}

apiVersion: v1
kind: Secret
metadata:
  name: json-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    backstage.io/kubernetes-id: {{ .Values.app_code }}
type: Opaque
stringData:
  credentials.json: {{ dict
    "type" "external_account"
    "audience" .Values.google.federation.audience
    "subject_token_type" "urn:ietf:params:oauth:token-type:jwt"
    "token_url" "https://sts.googleapis.com/v1/token"
    "service_account_impersonation_url" (printf "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/%s.gserviceaccount.com:generateAccessToken" (include "app_sa" .))
    "credential_source" (dict "file" "/var/run/secrets/gcp/token" "format" (dict "type" "text"))
    | toPrettyJson | quote }}

{{- end }}
