{{- if .Values.enabled }}

{{- if .Values.ingress.https }}

apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: google-cert
spec:
  domains:
    - {{ include "walker-chart.domain" . }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-tls
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ include "walker-chart.ip_name" . }}
    networking.gke.io/managed-certificates: google-cert
    networking.gke.io/v1beta1.FrontendConfig: gke-frontendconfig
spec:
  defaultBackend:
    service:
      name: nginx-svc
      port:
        number: 443

---

{{- end }}


{{- if .Values.ingress.http }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-http
spec:
  defaultBackend:
    service:
      name: nginx-svc
      port:
        number: 443

---
{{- end }}

{{- end }}

