{{- if and (.Values.enabled) (not .Values.local) }}

{{- if .Values.ingress.cert }}

apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: google-cert
  namespace: {{ .Release.Namespace }}
spec:
  domains:
    - {{ include "domain" . }}

{{- end }}

{{- end }}
