{{- if and (.Values.enabled) (not .Values.local) }}

{{- if or (.Values.ingress.enabled) (.Values.ingress.cert) }}
{{- if .Values.ingress.https }}

apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: google-cert
  namespace: {{ .Release.Namespace }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.app_code }}
  annotations:
    configsync.gke.io/cluster-name-selector: {{ include "primary_cluster" $ }}
spec:
  domains:
    - {{ include "domain" . }}

{{- end }}
{{- end }}

{{- end }}
