{{- if and (.Values.enabled) (.Values.nginx.enabled) }}

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-svc
    tier: frontend
  {{- if not .Values.local }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "gke-backendconfig"}'
    {{- if .Values.external_dns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "domain" . -}}.
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: nginx-dep
    
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 80

{{- end }}
