{{- if and (.Values.enabled) (.Values.nginx.enabled) }}

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-svc
    tier: frontend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "gke-backendconfig"}'
spec:
  type: ClusterIP
  selector:
    app: nginx-dep
    
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 80

{{- end }}
