{{- if and (.Values.enabled) (.Values.postgres.enabled) }}

apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: crunchydb
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.6-2
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.postgres.disk_size }}
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: {{ .Values.postgres.disk_size }}

---

apiVersion: v1
kind: Service
metadata:
  name: db-proxy
spec:
  type: CLusterIP
  selector:
    postgres-operator.crunchydata.com/instance-set: instance1
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: postgres

{{- end }}
