{{- if and (.Values.enabled) (.Values.postgres.enabled) }}

apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: crunchydb
spec:
  image: {{ .Values.postgres.image }}
  postgresVersion: {{ .Values.postgres.version }}
  {{- if .Values.postgres.init_sql }}
  databaseInitSQL:
    name: crunchydb-init-sql
    key: init.sql
  {{- end }}
  {{- if .Values.postgres.backup.gcs.enabled }}
  metadata:
    annotations:
      iam.gke.io/gcp-service-account: {{ .Values.postgres.backup.gcs.gcp_service_account | quote }}
  {{- end }}
  instances:
    - name: instance1
      replicas: {{ .Values.postgres.replicas }}
      {{- if .Values.linkerd.enabled }}
      metadata:
        annotations:
          linkerd.io/inject: enabled
      {{- end }}
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.postgres.disk_size }}
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - host crunchydb crunchydb 0.0.0.0/0 password
        postgresql:
          - 'max_connections = 500'
  backups:
    pgbackrest:
      image: {{ .Values.postgres.backup.image }}
      {{- if .Values.postgres.backup.gcs.enabled }}
      metadata:
        annotations:
          iam.gke.io/gcp-service-account: {{ .Values.postgres.backup.gcs.gcp_service_account | quote }}
      global:
        repo2-gcs-key-type: auto
        repo2-path: /pgbackrest/{{ .Release.Namespace }}/crunchydb/repo2
        repo2-retention-full: {{ .Values.postgres.backup.gcs.retention.full | quote }}
        repo2-retention-full-type: count
      {{- end }}
      repos:
      {{- if .Values.postgres.backup.gcs.enabled }}
      - name: repo2
        gcs:
          bucket: {{ required "REQUIRED: postgres.backup.gcs.bucket when postgres.backup.gcs.enabled" .Values.postgres.backup.gcs.bucket | quote }}
        schedules:
          full: {{ .Values.postgres.backup.gcs.schedules.full | quote }}
          differential: {{ .Values.postgres.backup.gcs.schedules.differential | quote }}
      {{- else }}
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: {{ .Values.postgres.disk_size }}
      {{- end }}

{{- if .Values.postgres.init_sql }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crunchydb-init-sql
  namespace: {{ .Release.Namespace }}
data:
  init.sql: |
{{ .Values.postgres.init_sql | indent 4 }}
{{- end }}

{{- end }}
