{{- if and (.Values.enabled) (.Values.postgres.enabled) }}

apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: crunchydb
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.6-2
  postgresVersion: 14
  instances:
    - name: instance1
      replicas: {{ .Values.postgres.replicas }}
      {{- if .Values.linkerd.enabled }}
      metadata:
        annotations:
          linkerd.io/inject: enabled
      {{- end }}
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.postgres.disk_size }}
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - host crunchydb crunchydb 0.0.0.0/0 password
        postgresql:
          - 'max_connections = 500'
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: {{ .Values.postgres.disk_size }}

{{- end }}
