{{- if and (.Values.enabled) (.Values.postgres.enabled) }}

apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: crunchydb
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.6-2
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.postgres.disk_size }}
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
      {{- if .Values.postgres.backup.type "volume" }}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: {{ .Values.postgres.disk_size }}

      {{- else if .Values.postgres.backup.type "gcs" }}
      configuration:
      - secret:
          name: pgo-gcs-creds
      global:
        repo1-path: /pgbackrest/postgres-operator/crunchydb-gcs/repo1
      repos:
      - name: repo1
        gcs:
          bucket: {{ .Values.postgres.backup.bucket }}
      {{- end }}

{{- end }}
