{{- if and (.Values.enabled) (.Values.api.use_pd) }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gce-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    backstage.io/kubernetes-id: {{ .Values.app_code }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "REQUIRED: api.disk_size" .Values.api.disk_size }}

{{- end }}
