{{- if and (.Values.enabled) (not .Values.local) }}
{{- if .Values.secrets.enabled }}

apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ include "app_project" . }}
  data:
    {{- if .Values.django.enabled }}
    - key: django-key
      name: django-key
      version: latest

    {{- if .Values.django.use_email }}
    - key: email-password
      name: email-password
      version: latest
    {{- end }}

    {{- if .Values.django.oauth_id }}
    - key: oauth-secret
      name: oauth-secret
      version: latest
    {{- end }}

    {{- end }}

    {{- if .Values.oauth.google.enabled }}
    - key: google-oauth-id
      name: google-oauth-id
      version: latest

    - key: google-oauth-secret
      name: google-oauth-secret
      version: latest

    {{- end }}

    {{- if .Values.oauth.google.sheets.enabled }}
    - key: google-oauth-creds
      name: google-oauth-creds
      version: latest
    {{- end }}

    {{- if .Values.oauth.github.enabled }}
    - key: github-oauth-id
      name: github-oauth-id
      version: latest

    - key: github-oauth-secret
      name: github-oauth-secret
      version: latest
    {{- end }}

    {{- if .Values.oauth.facebook.enabled }}
    - key: facebook-oauth-id
      name: facebook-oauth-id
      version: latest

    - key: facebook-oauth-secret
      name: facebook-oauth-secret
      version: latest
    {{- end }}

    {{- if .Values.oauth.twitter.enabled }}
    - key: twitter-api-key
      name: twitter-api-key
      version: latest

    - key: twitter-api-key-secret
      name: twitter-api-key-secret
      version: latest
    {{- end }}

    {{- if .Values.firebase.enabled }}
    - key: firebase-key
      name: firebase-key
      version: latest
    {{- end }}

    {{- if .Values.sendgrid.enabled }}
    - key: sendgrid-key
      name: sendgrid-key
      version: latest
    {{- end }}

    {{- if .Values.twilio.enabled }}
    - key: twilio-auth-token
      name: twilio-auth-token
      version: latest

    - key: twilio-account-sid
      name: twilio-account-sid
      version: latest

    {{- if .Values.twilio.flex.enabled }}
    - key: twilio-flex-workspace-id
      name: twilio-flex-workspace-id
      version: latest

    - key: twilio-flex-workflow-sid
      name: twilio-flex-workflow-sid
      version: latest
    {{- end }}

    {{- end }}

    {{- if .Values.agile.enabled }}
    - key: agile-crm-rest-key
      name: agile-crm-rest-key
      version: latest
    {{- end }}

    {{- if eq .Values.app_code "boatload" }}
    - key: api-key
      name: api-key
      version: latest
    {{- end }}

{{- end }}
{{- end }}


