{{- if .Values.selenium.enabled }}

apiVersion: batch/v1
kind: Job
metadata:
  name: selenium
  labels:
    app: selenium
spec:
  template:
    metadata:
      name: selenium
      labels:
        app: selenium
    spec:
      containers:
      - name: chrome
        image: selenium/standalone-chrome
      - name: app-tests
        image: {{ include "selenium_image" . }}
        env:
        - name: DOMAIN
          value: {{ include "subdomain" $ }}
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst

{{- end }}

