{{- if .Values.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ include "walker-chart.app_sa" . }}.gserviceaccount.com
  name: {{ .Values.app_code -}}-sa

{{- end }}
