{{- if .Values.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if not .Values.local }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "app_sa" . }}.gserviceaccount.com
  {{- end }}
  name: {{ .Release.Namespace -}}-sa

{{- end }}
