{{- if .Values.google.storage.enabled }}
{{- range .Values.google.storage.bucket_list }}

apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: {{ include "app_label" $ -}}-{{- .name }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project" $ }}
    cnrm.cloud.google.com/force-destroy: "false"
  labels:
    namespace: {{ $.Release.Namespace }}
    backstage.io/kubernetes-id: {{ $.Values.app_code }}
spec:
  cors:
    - origin: ["https://{{- include "domain" $ -}}"]
      responseHeader: ["Content-Type"]
      method: ["*"]
      maxAgeSeconds: 3600
  uniformBucketLevelAccess: true

---
{{- if .public }}

apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucketAccessControl
metadata:
  name: {{ include "app_label" $ -}}-{{- .name -}}-access
spec:
  bucketRef:
    name: {{ include "app_label" $ -}}-{{- .name }}
  entity: allUsers
  role: READER

---
{{- end }}

{{- end }}
{{- end }}
