---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: "{{ .Values.app_code }}-folder"
spec:
  displayName: "{{ .Values.app_code }}-folder"
  folderRef:
    external: {{ required "Must provide parent folder name for application" .Values.google.parent_folder_id }}

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  labels:
    name: "s5-{{ .Values.app_code }}"
  name: "s5-{{ .Values.app_code }}"
spec:
  displayName: S5 bootstrap service account for the {{ .Values.app_code }} App.

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: "s5-{{ .Values.app_code }}-wi"
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: "s5-{{ .Values.app_code }}"
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{ .Values.google.gke_project }}.svc.id.goog[cnrm-system/cnrm-controller-manager-{{ .Values.app_code }}-cpl]

#Allow bootstrap s5 account to create s6 namespace service accounts within the governance service account project
---
  apiVersion: iam.cnrm.cloud.google.com/v1beta1
  kind: IAMPolicyMember
  metadata:
    name: "s5-{{ .Values.app_code }}-sact-iam"
  spec:
    member: serviceAccount:s5-{{ .Values.app_code }}@{{ .Values.google.iac_project}}.iam.gserviceaccount.com
    role: roles/iam.serviceAccountAdmin
    resourceRef:
      apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
      kind: Project
      external: "projects/{{ .Values.google.iac_project }}"

#Allow bootstrap s5 account to set IAM within the subtenant folder
---
  apiVersion: iam.cnrm.cloud.google.com/v1beta1
  kind: IAMPolicyMember
  metadata:
    name: "s5-{{ .Values.app_code }}-folder-iam"
  spec:
    member: serviceAccount:s5-{{ .Values.app_code }}@{{ .Values.google.iac_project}}.iam.gserviceaccount.com
    role: roles/resourcemanager.folderIamAdmin
    resourceRef:
      apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
      kind: Folder
      external: "folders/{{ .Values.google.app_folder_id }}"
