{{- $root := . -}}

{{- range .Values.tenants }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $root.Values.project }}
  destination:
    namespace: {{ .name }}-cd
    server: {{ $root.Values.destination.server }}
  source:
    path: ''
    repoURL: {{ $root.Values.source.repoURL }}
    targetRevision: 0.0.32
    chart: web-app
    helm:
     valueFiles:
        - values/{{- .name -}}/{{- $root.Values.lifecycle -}}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

---

{{- end }}
