proj_identifier: v1

app_code: bl

google:
  domain: boatload.us

secrets:
  enabled: true

twilio:
  enabled: true
  number: "12692155688"

firebase:
  enabled: false

airtable:
  base_id: "appDYtZ8GHWNDnltu"
