{{- if and (.Values.enabled) (.Values.api.enabled) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dep
  labels:
    app: api-dep
    tier: backend
spec:
  replicas: {{ required "API Replicas required" .Values.api.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: api-dep
  template:
    metadata:
      labels:
        app: api-dep
    spec:
      serviceAccountName: {{ .Values.app_code -}}-sa
      restartPolicy: Always
      containers:
      - name: api
        image: {{ include "walker-chart.api_image" . }}
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: {{ required "API Memory Requests Required" .Values.api.memory.request }}
            cpu: {{ required "API CPU Requests Required" .Values.api.cpu.request }}
          limits:
            memory: {{ required "API Memory Limits Required" .Values.api.memory.limit }}
            cpu: {{ required "API CPU Limits Required" .Values.api.cpu.limit }}

        {{- if ne .Values.app_code "bl" }}
        livenessProbe:
          httpGet:
            path: /api/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /api/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        {{- end }}

        {{- if and (not .Values.db.proxy) (.Values.db.local) }}
        command: ["/bin/sh"]
        args: ["-c", "./init_db.sh && gunicorn -b 0.0.0.0:8000 {{ .Values.api.label -}}.wsgi"]
        {{- end }}

        env:
        - name: LIFECYCLE
          value: {{ .Values.lifecycle }}
        - name: USE_GCS
          value: "true"
        - name: DOMAIN
          value: {{ include "walker-chart.domain" . }}
        - name: STATIC_BUCKET
          value: {{ include "walker-chart.bucket" . }}

        {{- if .Values.django.enabled }}
        - name: DJANGO_KEY
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: django-key

        {{- if .Values.django.email }}
        - name: DJANGO_EMAIL
          value: {{ .Values.django.email }}
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: email-password
        {{- end }}

        {{- if .Values.django.oauth }}
        - name: OAUTH_ID
          value: {{ .Values.django.oauth_id }}
        - name: OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: oauth-secret
        {{- end }}

        {{- if .Values.sendgrid.enabled }}
        - name: SENDGRID_EMAIL
          value: {{ .Values.sendgrid.email }}
        - name: SENDGRID_KEY
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: sendgrid-key
        {{- end }}
        {{- end }}

        {{- if .Values.db.proxy }}
        - name: USE_PROXY
          value: "true"
        - name: DB_NAME
          value: {{ include "walker-chart.db_name" . }}
        - name: DB_USER
          value: {{ include "walker-chart.app_sa" . }}
        {{- end }}

        {{- if .Values.twilio.enabled }}
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: twilio-auth-token
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: twilio-account-sid

        {{- if eq .Values.app_code "cgs" }}
        - name: TWILIO_NUMBER_IL
          value: '{{ required "IL Phone number required for CGS" .Values.twilio.numbers.il }}'
        - name: TWILIO_NUMBER_WA
          value: '{{ required "WA Phone number required for CGS" .Values.twilio.numbers.wa }}'
        - name: TWILIO_NUMBER_SID_IL
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: twilio-number-sid-il
        - name: TWILIO_NUMBER_SID_WA
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: twilio-number-sid-wa

        {{- else }}
        - name: TWILIO_NUMBER
          value: '{{ required "Phone number required if using Twilio" .Values.twilio.number }}'
        - name: TWILIO_NUMBER_SID
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: twilio-number-sid
        {{- end }}

        {{- end }}

        {{- if eq .Values.app_code "bl" }}
        - name: BASE_ID
          value: '{{ required "Base ID required to use Airtable" .Values.airtable.base_id }}'
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: api-key
        {{- end }}

        ports:
        - containerPort: 8000
          name: api-port

      {{- if .Values.db.proxy }}
      - name: proxy
        image: "{{ .Values.db.proxy_version }}"
        imagePullPolicy: Always
        command:
        - /cloud_sql_proxy
        - -instances={{- include "walker-chart.db_project" . -}}:{{- required "Region Required" .Values.google.region -}}:{{- .Values.app_code -}}-{{- required "DB Instance Required" .Values.db.instance -}}=tcp:127.0.0.1:5432
        - -enable_iam_login
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      {{- end }}

{{- end }}


