
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-dep
  minReplicas: {{ .Values.k8s.api.replicas }}
  maxReplicas: {{ .Values.k8s.api.max_replicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: {{ .Values.k8s.api.target_mem }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.k8s.api.target_cpu }}

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-dep
  minReplicas: {{ .Values.k8s.nginx.replicas }}
  maxReplicas: {{ .Values.k8s.nginx.max_replicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: {{ .Values.k8s.nginx.target_mem }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.k8s.nginx.target_cpu }}


