{{- if .Values.enabled }}

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gke-backendconfig
spec:
  securityPolicy:
    name: us-only

  {{- if or (ne .Values.lifecycle "ops") (ne .Values.lifecycle "dev") }}
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
  {{- end }}

{{- end }}
