apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cilium-controller
spec:
  endpointSelector: {}

  ingress:
    - fromEndpoints:
        - {}

  egress:
    - toEndpoints:
        - {}
