apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: gke-frontendconfig
spec:
  sslPolicy: new-tls
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT

