{{- if and (.Values.enabled) (.Values.secrets.enabled) }}

apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secrets-manager
spec:
  backendType: gcpSecretsManager
  projectId: {{ include "walker-chart.gke_project" . }}
  data:
    {{- if .Values.django.enabled }}
    - key: django-key
      name: django-key
      version: latest

    {{- if .Values.django.email }}
    - key: email-password
      name: email-password
      version: latest
    {{- end }}

    {{- if .Values.django.oauth_id }}
    - key: oauth-secret
      name: oauth-secret
      version: latest
    {{- end }}

    {{- end }}

    {{- if .Values.firebase.enabled }}
    - key: firebase-key
      name: firebase-key
      version: latest
    {{- end }}

    {{- if .Values.sendgrid.enabled }}
    - key: sendgrid-key
      name: sendgrid-key
      version: latest
    {{- end }}

    {{- if .Values.twilio.enabled }}
    - key: twilio-auth-token
      name: twilio-auth-token
      version: latest

    - key: twilio-account-sid
      name: twilio-account-sid
      version: latest

    {{- if eq .Values.app_code "cgs" }}
    - key: twilio-number-sid-il
      name: twilio-number-sid-il
      version: latest

    - key: twilio-number-sid-wa
      name: twilio-number-sid-wa
      version: latest

    {{- else }}
    - key: twilio-number-sid
      name: twilio-number-sid
      version: latest
    {{- end }}
    {{- end }}

    {{- if eq .Values.app_code "bl" }}
    - key: api-key
      name: api-key
      version: latest
    {{- end }}

{{- end }}


