apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictNamespaces
metadata:
  name: restrict-namespaces
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    restrictedNamespaces:
      - "default"
      - "kube-public"
      - "kube-system"
      - "gatekeeper-system"
      - "argo-cd"
      - "argo-events"
      - "argo-rollouts"
      - "argo-workflows"
