
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ include "lifecycle" $ -}}-{{- .Values.app_code -}}-app-workload
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "sa_project_id" $ }}
spec:
  displayName: "{{ include "lifecycle" $ }} {{ .Values.app_code }} workload service account"

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ include "lifecycle" $ -}}-{{- .Values.app_code -}}-app-workload-wi
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "gke_project_id" $ }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ include "lifecycle" $ -}}-{{- .Values.app_code -}}-app-workload
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{- include "gke_project_id" $ -}}.svc.id.goog[{{- include "lifecycle" $ -}}-{{- .Values.app_code -}}/{{- .Values.app_code -}}-sa]


