
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ include "lifecycle" $ -}}-{{- .Values.app_code -}}-infra-admin
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "sa_project_id" $ }}
spec:
  displayName: "{{ include "lifecycle" $ }} {{ .Values.app_code }} infra admin service account"

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ include "lifecycle" $ -}}-{{- .Values.app_code -}}-infra-admin
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "gke_project_id" $ }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ include "lifecycle" $ -}}-{{- .Values.app_code -}}-infra-admin
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{- include "gke_project_id" $ -}}.svc.id.goog[cnrm-system/cnrm-controller-manager-{{- include "lifecycle" $ -}}-{{- .Values.app_code -}}-infra-admin]

