{{- if not .Values.local }}

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gke-backendconfig
spec:
  # securityPolicy:
  #   name: us-only

  cdn:
    enabled: false
    cachePolicy:
      includeHost: true
      includeProtocol: true

{{- end }}
