{{- if .Values.use_web }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payout-deployment
  labels:
    app: payout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payout
  template:
    metadata:
      labels:
        app: payout
    spec:
      volumes:
      - name: input
        configMap:
          name: input

      containers:
      - name: server
        image: {{ include "server_image" . }}

        volumeMounts:
        - name: input
          mountPath: /
          readOnly: true
          
        ports:
        - containerPort: 8080

        {{- if false }}
        livenessProbe:
          httpGet:
            path: /healthz/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /healthz/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        {{- end }}

{{- end }}
