{{- if .Values.ingress.https }}

apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: google-cert
spec:
  domains:
  - {{ required "REQUIRED: domain" .Values.domain }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payout-tls
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ include "ip_name" . }}
    networking.gke.io/managed-certificates: google-cert
    networking.gke.io/v1beta1.FrontendConfig: gke-frontendconfig
spec:
  defaultBackend:
    service:
      name: payout-svc
      port:
        number: 443

---

{{- end }}


{{- if .Values.ingress.http }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payout-http
spec:
  defaultBackend:
    service:
      name: payout-svc
      port:
        number: 443

---
{{- end }}


