
apiVersion: batch/v1
kind: Job
metadata:
  name: payout-job
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: payout-calculate
        image: us-central1-docker.pkg.dev/tp2-app-project/prod/api:latest
        command:
          - bash
          - -c
          - /haskell/payout < /input
        volumeMounts:
        - name: input
          mountPath: /
          readOnly: true
      volumes:
      - name: input
        configMap:
          name: input
      restartPolicy: Never

