apiVersion: v1
kind: Service
metadata:
  name: payout-svc

  {{- if not .Values.local  }}
  annotations:
    {{- if or (.Values.ingress.http) (.Values.ingress.https) }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
    cloud.google.com/backend-config: '{"default": "gke-backendconfig"}'
  {{- end }}

spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: payout
