{{ if .Values.config_connect.project }}

apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/auto-create-network: "false"
  name: {{ .Values.app_code }}-project
spec:
  name: "{{ .Values.app_project }}"
  folderRef:
    external: {{ .Values.google.parent_folder }}
  #billingAccountRef:
  #  external: ""

{{ end }}
