{{ if .Values.config_connect.iam }}

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
   cnrm.cloud.google.com/project-id: {{ required "iac_project REQUIRED" .Values.iac_project }}
  name: "s6-{{ required "app_code REQUIRED" .Values.app_code }}-be"
spec:
  displayName: S6 service account for the {{ .Values.app_code }}-be namespace.

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: "s6-{{ .Values.app_code }}-be-wi"
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: "s6-{{ .Values.app_code }}"
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - "serviceAccount:{{ required "gke_project REQUIRED" .Values.gke_project }}.svc.id.goog[cnrm-system/cnrm-controller-manager-{{ .Values.app_code }}-be]"

---

  apiVersion: iam.cnrm.cloud.google.com/v1beta1
  kind: IAMPolicyMember
  metadata:
    name: "s6-{{ .Values.app_code }}-be-folder-iam"
  spec:
    member: "serviceAccount:s6-{{ .Values.app_code }}-be@{{ .Values.iac_project }}.iam.gserviceaccount.com"
    role: roles/resourcemanager.projectCreator
    resourceRef:
      apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
      kind: Folder
      external: folders/{{ required "google.parent_folder_id REQUIRED" .Values.google.parent_folder_id }}

---

  apiVersion: iam.cnrm.cloud.google.com/v1beta1
  kind: IAMPolicyMember
  metadata:
    name: "s6-{{ .Values.app_code }}-be-registry-iam"
  spec:
    member: "serviceAccount:s6-{{ .Values.app_code }}-be@{{ .Values.iac_project }}.iam.gserviceaccount.com"
    role: roles/artifactregistry.reader
    resourceRef:
      apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
      kind: Project
      external: "projects/{{ required "registry_project REQUIRED" .Values.registry_project }}"

{{ end }}
